### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by millette** [pfrazee/multicb#5]
Can we have a license for this module? It's used by dat-node and many ssb modules. There's no license file or field in package.json which I suspect is a simple oversight.

----

[FOSSA](http://fossa.io) has found issues in this repo:

 - **UNLICENSED_DEPENDENCY:** multicb$1.2.2

Generated by [FOSSA](http://fossa.io) on 07/08/2018

Reported by FOSSA user: millette

**Comment by pfrazee** [comment]
Yeah, done. Thanks
